{
 "title": "Databricks Runs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "run",
    "label": "Run Name",
    "query": {
     "query": "label_values(databricks_exporter_runs_total, run_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Fail Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(databricks_exporter_runs_total{result_state=\"FAILED\"}) / count(databricks_exporter_runs_total)"
    }
   ]
  },
  {
   "title": "Runs By Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job_id,run_name)(databricks_exporter_runs_total)",
     "legendFormat": "{{run_name}}"
    }
   ]
  },
  {
   "title": "Runs By State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (life_cycle_state)(databricks_exporter_runs_total)",
     "legendFormat": "{{life_cycle_state}}"
    }
   ]
  }
 ]
}