name: Publish ARM
on: [push]
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: efrat19/databricks-runs-exporter
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "amd64-latest,amd64-${{ github.sha }}"
          context: src
  push-manifest:
    runs-on: [ubuntu-latest]
    needs:
      - build-amd64
    steps:
      - name: setup docker(Without version)
        uses: docker-practice/actions-setup-docker@master
      - run: |
          docker manifest create efrat19/databricks-runs-exporter:latest efrat19/databricks-runs-exporter:amd64-latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker manifest push efrat19/databricks-runs-exporter:latest
